-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 17:15:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pamacri
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pamacri
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `pamacri` DEFAULT CHARACTER SET utf8 ;
USE `pamacri` ;

-- -----------------------------------------------------
-- Table `pamacri`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pamacri`.`Proveedor` (
  `idProveedor` INT AUTO_INCREMENT,
  `rutProveedor` VARCHAR(70) NOT NULL,
  `nombreProveedor` VARCHAR(70) NOT NULL,
  `plazo` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pamacri`.`Cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pamacri`.`Cheque` (
  `idCheque` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME,
  `nroCheque` VARCHAR(45) NOT NULL,
  `monto` INT ,
  `cobro` DATETIME,
  `estado` VARCHAR(45),
  `nroFactura` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT ,
  PRIMARY KEY (`idCheque`),
  
  CONSTRAINT `fk_Cheque_Proveedor` FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `pamacri`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pamacri`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pamacri`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  `nomUsuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- SUBIDA DE DATOS DESDE ARCHIVO DE PROVEEDORES ( EXCEL )

LOAD DATA INFILE "Carga_Proveedores.csv" INTO TABLE pamacri.Proveedor
FIELDS TERMINATED BY ';'
LINES TERMINATED BY  '\r\n' 
IGNORE 1 LINES
(@dummy,@nombreProveedor,@rutProveedor,@plazo,@tipo)
SET nombreProveedor = @nombreProveedor,
rutProveedor = @rutProveedor,
plazo = @plazo,
tipo = @tipo;


LOAD DATA INFILE "Carga_Cheques.csv" INTO TABLE pamacri.Cheque
FIELDS TERMINATED BY ';'
LINES TERMINATED BY  '\r\n' 
IGNORE 1 LINES
(@fecha,@dummy,nroCheque,nroFactura,@monto,@dummy,@cobro,@proveedor)
SET Proveedor_idProveedor = (SELECT idProveedor FROM proveedor WHERE nombreProveedor = @proveedor),
fecha = @fecha, -- STR_TO_DATE(@fecha,'%d/%m/%Y'),
monto = REPLACE(REPLACE(@monto,'$',''),'.',''),
cobro = @cobro; -- STR_TO_DATE(@cobro,'%d/%m/%Y');