-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 17:15:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pamacri
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pamacri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pamacri` DEFAULT CHARACTER SET utf8 ;
USE `pamacri` ;

-- -----------------------------------------------------
-- Table `pamacri`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pamacri`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `rutProveedor` VARCHAR(45) NOT NULL,
  `nombreProveedor` VARCHAR(45) NOT NULL,
  `plazo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pamacri`.`Cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pamacri`.`Cheque` (
  `idCheque` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `nroCheque` VARCHAR(45) NOT NULL,
  `monto` INT NULL,
  `cobro` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `nroFactura` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idCheque`),
  INDEX `fk_Cheque_Proveedor_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Cheque_Proveedor`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `pamacri`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pamacri`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pamacri`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  `nomUsuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
